Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2022-09, with the labels that each got.

#145 Add ValueProxyExtensions and FixGrabWorld, update PasteInvidious and InspectorScroll
  manifest.json
Labels: author PR

#146 Add version v1.2.0 of NeosModSettings
  manifest.json
Labels: author PR

#148 add ReArmature version 1.1
  manifest.json
Labels: author PR

#147 add KeepGlobalTransformToggle
  manifest.json
Labels: mod author PR

#153 added SlotLessWorkerInterfaces
  manifest.json
Labels: mod author PR

#115 Add ReFract
  manifest.json
Labels: non-mod-author PR

#111 Add Proxify
  manifest.json
Labels: non-mod-author PR

#155 Add automated new mod version notifications
  .github/workflows/release-notifications.yml
  .gitignore
  gen_notif.py
  gen_readme.py
  util.py
Labels: enhancement

#157 Fix a few minor GHA notification issues
  .github/workflows/release-notifications.yml
Labels: broken

#156 Add v1.3.0 of UserJoinLeaveNotifications
  manifest.json
Labels: mod author PR

#158 Hopefully the last minor notification fixes
  gen_notif.py
  schema.json
Labels: broken

#163 update LogixPulseVisualizer
  manifest.json
Labels: mod author PR

#164 Adding my mods to the manifest
  manifest.json
Labels: mod author PR

#165 Fix bad embed gen
  gen_notif.py
Labels: broken
