Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2022-12, with the labels that each got.

#188 Clarify `deprecated` flag usage
  .github/pull_request_template.md
Labels: documentation

#187 Add 1.1.0 of NeosBetterGizmos
  manifest.json
Labels: mod author PR

#195 Update ColorDrop to version 1.2.0
  manifest.json
Labels: mod author PR

#193 Add NeosVideoPlayerFix v4.0.0
  manifest.json
Labels: mod author PR, non-mod-author PR

#192 Add BetterInventoryBrowser
  manifest.json
Labels: mod author PR

#197 Add DisableLegacyInventory
  manifest.json
Labels: mod author PR

#189 Add LocalStorage 1.1.0
  manifest.json
Labels: non-mod-author PR

#199 Add DesktopHandSwitch
  manifest.json
Labels: mod author PR

#198 More mods and updates!
  manifest.json
Labels: mod author PR
