Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2022-08, with the labels that each got.

#133 Update DynVarGenerator versions
  manifest.json
Labels: Author PR

#130 Adding Webservers mod to manifest.json
  manifest.json
Labels: author PR

#110 Add Nodentify
  manifest.json
Labels: non-author PR

#140 Update LeCloutPanda's mods
  manifest.json
Labels: non-author PR

#141 Add CustomLogiXTypes
  manifest.json
Labels: author PR
