Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2023-06, with the labels that each got.

#297 add CustomUILib
  manifest.json
Labels: mod author PR

#295 Add ComponentSearchWizard v1.1.1
  manifest.json
Labels: mod author PR

#302 fix iTrackerFix download link
  manifest.json
Labels: broken, non-mod-author PR

#298 Update CustomUILib
  manifest.json
Labels: mod author PR

#293 add CreateWorldConfig
  manifest.json
Labels: mod author PR

#294 Add ImportDefaultsChange v1.0.0 and VRLogixRotateFix v1.0.1
  manifest.json
Labels: mod author PR

#284 Add ComponentAttacherRecents, BoundedUIX and DynVarSpaceTree updates + new AlternatingSessionUserList and StopNarcissistParents
  manifest.json
Labels: mod author PR

#282 Add HeadlessCurbYourUndoManager v1.0.4
  manifest.json
Labels: mod author PR

#303 Update createworldconfig
  manifest.json
Labels: mod author PR

#304 add ChildrenAlsoMatter
  manifest.json
Labels: mod author PR

#305 Add ColorMyPanels v1.0.0
  manifest.json
Labels: mod author PR

#308 add AcceptEquivalentDelegates
  manifest.json
Labels: mod author PR

#307 Add manifest flag for android platforms
  schema.json
Labels: enhancement

#312 Add Audio Category
  manifest.json
  schema.json
Labels: enhancement

#313 Change several audio mods from Misc to Audio
  manifest.json
Labels: enhancement, non-mod-author PR

#311 Add The Show Must Go On release
  manifest.json
Labels: mod author PR

#315 Update captureprivateui
  manifest.json
Labels: mod author PR

#319 Add v1.3.0 of NeosModSettings
  manifest.json
Labels: mod author PR

#322 Add PermissionControl 1.0.0
  manifest.json
Labels: mod author PR

#301 Add DontDriveMeMad v1.0.0
  manifest.json
Labels: non-mod-author PR

#316 Add AudioClipWizard v1.0.0
  manifest.json
Labels: mod author PR

#321 Add AccessibleFullBodyCalibrator v1.0.1
  manifest.json
Labels: mod author PR

#325 add ArrowExpanders
  manifest.json
Labels: mod author PR

#324 add SlotlessInspectorOpener
  manifest.json
Labels: mod author PR

#309 add ReduceAnimation v1.3
  manifest.json
Labels: mod author PR

#328 Update AudioClipWizard to v1.0.1
  manifest.json
Labels: mod author PR

#329 Add Safe Mode mod
  manifest.json
Labels: mod author PR

#323 add ExposeEditorlessMembers
  manifest.json
Labels: mod author PR

#320 Deprecate AlternatingSessionUserList in favor of added SessionTabOverhaul release
  manifest.json
Labels: mod author PR

#327 recagorized some entries
  manifest.json
  schema.json
Labels: enhancement
