Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2023-04, with the labels that each got.

#238 Add CustomLogixBrowser to the manifest
  manifest.json
Labels: mod author PR

#250 Add ComponentAttacher* Updates
  manifest.json
Labels: mod author PR

#251 Add Simulstart and NoAprilFools
  manifest.json
Labels: mod author PR

#243 Add TNMTMISTYFANLTTSSYCREANKNOWSBIYHWYP v1.1.0
  manifest.json
Labels: mod author PR

#245 Add NML 1.12.5 and 1.12.6
  manifest.json
Labels: non-mod-author PR

#252 Add Atom Feed generator
  .github/workflows/atom-feed-update.yml
  atom_feeder.py
Labels: enhancement

#242 add OpenLinkedVariableSpace v1.0.1
  manifest.json
Labels: mod author PR

#257 Fix Atom Feeder
  atom_feeder.py
Labels: broken, enhancement

#256 Update actions/checkout v1 and v2
  .github/workflows/lint.yml
Labels: enhancement

#244 Add CreateNewUIX 1.1.0
  manifest.json
Labels: mod author PR

#261 Merge Update-Atom and Generate-Markdown workflows
  .github/workflows/markdown-gen.yml
  .github/workflows/update-github-pages.yml
Labels: enhancement

#260 update OpenLinkedVariableSpace
  manifest.json
Labels: mod author PR

#263 Updated GenericTypeType to 0.1.2
  manifest.json
Labels: mod author PR

#265 add 🍀
  manifest.json
Labels: mod author PR

#264 Add SessionUrlJoin
  manifest.json
Labels: mod author PR

#267 Add ColorMyLogiX v1.1.0
  manifest.json
Labels: mod author PR

#246 Add BetterInventoryBrowser 0.4.1
  manifest.json
Labels: non-mod-author PR

#247 Add KeepGlobalTransformToggle 1.1.2
  manifest.json
Labels: non-mod-author PR

#271 Update CustomLogixBrowser to v1.1.0
  manifest.json
Labels: mod author PR

#272 Add AvatarCreatorUtils and DontMoveInspectors
  manifest.json
Labels: mod author PR
