Repository neos-modding-group/neos-mod-manifest, pull requests merged in 2023-03, with the labels that each got.

#234 Deprecate GifImporter
  manifest.json
Labels: non-mod-author PR

#228 Add NeosPTTKeybinds 1.2.2
  manifest.json
Labels: mod author PR

#230 Added new version of DynVarGenerator
  manifest.json
Labels: mod author PR

#217 Add NeosLinuxExportFix
  manifest.json
Labels: mod author PR

#236 Add MeshAutoReimport and update CustomLogiXTypes
  manifest.json
Labels: mod author PR

#237 Add filename validation
  manifest.json
  schema.json
Labels: enhancement

#239 Add CreateNewUIX
  manifest.json
Labels: mod author PR

#241 Add ContactsMinus Mod
  manifest.json
Labels: mod author PR
